### ISSUE TITLE
Not compatible with Quarkus 2.6.x

### ISSUE THREAD

**Issue by hermannpencole** [quarkiverse/quarkus-kerberos#37]
When i use quarkus-kerberos, it is work perfectly with version of quarkus 2.5.x.
But not with version 2.6.x.
I have this stack 
2022-01-08 00:15:41,298 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to load steps from class io.quarkiverse.kerberos.deployment.devservices.KerberosDevServicesProcessor
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:93)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:456)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:67)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:105)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: java.lang.RuntimeException: Failed to load steps from class io.quarkiverse.kerberos.deployment.devservices.KerberosDevServicesProcessor
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:199)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:108)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:328)
	... 9 more
Caused by: java.lang.IllegalArgumentException: Unsupported method parameter java.util.Optional<io.quarkus.deployment.builditem.DevServicesSharedNetworkBuildItem> at java.util.Optional<io.quarkus.deployment.builditem.DevServicesSharedNetworkBuildItem> devServicesSharedNetworkBuildItem of public io.quarkiverse.kerberos.deployment.devservices.KerberosDevServicesConfigBuildItem io.quarkiverse.kerberos.deployment.devservices.KerberosDevServicesProcessor.startKerberosContainer(java.util.Optional,io.quarkus.deployment.annotations.BuildProducer,io.quarkiverse.kerberos.deployment.KerberosBuildTimeConfig,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.deployment.logging.LoggingSetupBuildItem) of class io.quarkiverse.kerberos.deployment.devservices.KerberosDevServicesProcessor
	at io.quarkus.deployment.ExtensionLoader.reportError(ExtensionLoader.java:949)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFromClass(ExtensionLoader.java:699)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:197)
	... 11 more

**Comment by gsmet** [comment]
Thanks for reaching out. I just checked and this extension is not in our Ecosystem CI, thus why we missed the compatibility issue.
I will add it and work on a fix.

**Comment by gsmet** [comment]
https://github.com/quarkiverse/quarkus-kerberos/pull/38 fixes it.

I'm releasing 0.6.0, it should be available on Maven Central soon.
